[package]
name = "nfc"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-normalization = "0.1.22"
walkdir = "2.3.3"
pico-args = "0.5.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
